name: Netflix API CD

on:
  push:
    branches: [master]

jobs:
  test:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: YOUR_HOST
        username: root
        key: ${{ secrets.KEY }}
        script: |
          cd netflix/
          git pull
          systemctl restart gunicorn.service